### ISSUE TITLE
Finish Dynmap Implementation

### ISSUE THREAD

**Issue by cjburkey01** [cjburkey01/ClaimChunk#1]
Actually get it to show area markers.

**Comment by ExDomino** [comment]
I would like on my server to color all chunks that players own by your mod in green.
Do you plan to make that possible?

**Comment by cjburkey01** [comment]
If I manage to get Dynmap implemented, I’ll make the colors available to change in the config.

**Comment by cjburkey01** [comment]
I'm going to put this on hold for a little bit. I need to make myself a little more familiar with the API

**Comment by cjburkey01** [comment]
Ok, I'm working on this again (somewhat). As it stands on the subject of color, I think I'll have a default color and a permission for players to be able to change their color.

**Comment by cjburkey01** [comment]
I am planning now that this will actually be implemented using the system of events proposed in https://github.com/cjburkey01/ClaimChunk/issues/58 and will be included in a separate plugin called ClaimChunk Addons instead

**Comment by jakeryang** [comment]
Is there an update on this issue? I would love to have Dynmap support

**Comment by cjburkey01** [comment]
Events and such are the next feature once I get SQL support going and after that it shouldn't be too much work to implement, so I don't think it's too far off now. After all, I've only had this planned for _two years_

**Comment by cjburkey01** [comment]
https://www.spigotmc.org/resources/dynmap-claimchunk.71093/
