### ISSUE TITLE
protection

### ISSUE THREAD

**Issue by florosss** [cjburkey01/ClaimChunk#100]
Spigot Version: Spigot-9de398a-9c887d4
ClaimChunk Version: 0.0.15

Hello. I have checked your plugin. I have found some issues in the protection: - vehicules (minecart and boat), - mobile chests (on donkey or minecart), - some entities (items in itemframe and on armor stand), - 
 passive mobs (with projectile weapon). Can you release a patch for this points ? Thanks by advance.

**Comment by cjburkey01** [comment]
Should be fixed in https://github.com/cjburkey01/ClaimChunk/commit/da9d1c2828f08d3b2eb55f4ac8d2f32c02e9e356
