### ISSUE TITLE
Spread prevention protection

### ISSUE THREAD

**Issue by Xm4g1kZzXj0k3** [cjburkey01/ClaimChunk#101]
Hi,
i want purpose a new feature, fire spread prevention.

Fire could spread in a claimed chunk, and bypass the protection of the chunk.
With this bug, a claimed chunk isn't safe from griefer attack.

Tested version: 0.0.17

Thanks.

**Comment by cjburkey01** [comment]
Fire spread is entirely blocked within claimed chunks as of https://github.com/cjburkey01/ClaimChunk/commit/30b710118056d842c2243187631d4834a39357ef.

Did you want only to prevent fire spreading _into_ claimed chunks but allow fire to spread within claimed territory?

**Comment by cjburkey01** [comment]
I'm going to mark this as closed, let me know if you had different intended behavior.
