### ISSUE TITLE
Vanish

### ISSUE THREAD

**Issue by testablebox048** [cjburkey01/ClaimChunk#109]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [Players see that I went into there chunks in vanish]

**Describe the solution you'd like**
Can we make it when you are in vanish from players that they don't get a notifications that I went into there claims?

**Describe alternatives you've considered**
Make this a true or false in config

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/52344eebb738cb49c75efb7ec1672549271cb364
