### ISSUE TITLE
To long of a command Claim land

### ISSUE THREAD

**Issue by testablebox048** [cjburkey01/ClaimChunk#110]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [Everyone in the server has to do /claimchunk claim and young people can't remember that well. Then I have to explain it over and over again.]

**Describe the solution you'd like**
Solutions:
1. Make it when you place a special type of block in a chunk it claims the chunk .
2. Make the command more simple.
3. Bind it to a tool
4. Maybe have a command like /claim land
5. Put all of these solutions into one and make it where you can choose in config

**Comment by cjburkey01** [comment]
The `/chunk claim` command can also be used to claim chunks and there are plugins that let you bind commands to items (and possibly blocks?) so you could use those.

**Comment by testablebox048** [comment]
/chunk claim does not work

like a bucket of water and it goes back to normal after its used

**Comment by cjburkey01** [comment]
`/chunk claim` works for me, how’s it not working? Does it say command not found? It’s been a feature since I rewrote commands in like 0.0.5 or some early version like that, what version of claimchunk are you running?

**Comment by testablebox048** [comment]
Version .12 because I use 1.12 minecraft

**Comment by cjburkey01** [comment]
You’ll want to use 0.0.18 as it’s the latest version, but `/chunk claim` should still work in 0.0.12

**Comment by cjburkey01** [comment]
I'm going to close this because these suggestions could be implemented using other plugins. As for `/chunk claim`, no one else seems to be having any issues. This may be a weird question but are you using _this_ chunk claiming plugin? It sounds like you are but it never hurts to double check.
