### ISSUE TITLE
Could not pass event (with suggested fix)

### ISSUE THREAD

**Issue by Drachionix** [cjburkey01/ClaimChunk#113]
**Versions**
Spigot Version:
ClaimChunk Version: 0.0.18-Snapshot

**Describe the bug**
Console error with nullpointer exception

**To Reproduce**
1. /chunk info in non-claimed chunk when you do not have any chunks claimed
2. look at console

**Expected behavior**
no error

**Additional context**
there's a nullpointer exception in the getChunkOwner function bc claimedChunks.get(pos) == null (line 115/116 in data/newdata/JsonDataHandler.java)

**Comment by cjburkey01** [comment]
Thanks, I wouldn't have caught that myself lol

Fixed in https://github.com/cjburkey01/ClaimChunk/commit/96a19f1698e0c09860f21f93c6a619feb5354ee3
