### ISSUE TITLE
Give a Plot to a Player -- ClaimChunk as a Plotsystem

### ISSUE THREAD

**Issue by JaHollYT** [cjburkey01/ClaimChunk#114]
**Is your feature request related to a problem? Please describe.**
So, i want to use ClaimChunk as a Plotsystem on my Roleplay Server cause other Systems like Towny have incompabilities with some Plugin. 

**Describe the solution you'd like**
So with the Command /chung give Playername. I can give the Chunk completely to another Player. ( In the Roleplay i am the Landlord an i sell Chunks to Players actually with Towny, but as mentioned there are some Problems.
Also it would be cool to set a chunk forsale with a price(/chunk forsale price) that other Players can only claim it when they have enough money.

**Comment by cjburkey01** [comment]
I can offer the `/chunk give` command but I probably won't implement setting chunks for sale because it seems a little out of the scope of this plugin.

**Comment by JaHollYT** [comment]
/chunk give ist fine :)
To use ClaimChunk for a Town system is not needet tosell Chunks, i look forward to the Update!

**Comment by cjburkey01** [comment]
Added `/chunk give <player>` in https://github.com/cjburkey01/ClaimChunk/commit/164c305dff0a0373d4a16365cee8ba971d28b074

This should be available with 0.0.20 when it is released.
