### ISSUE TITLE
protected unclaimed chunks

### ISSUE THREAD

**Issue by stuee147** [cjburkey01/ClaimChunk#118]
**Versions**
Spigot Version:1.15
ClaimChunk Version:0.0.18

**Describe the bug**
normal players are unable to place or break blocks or interact with anything like doors or chests in unclaimed chunks the blockUnclaimedChunks is set to false 

**To Reproduce**
1. just installing plugin and starting server

**Expected behavior**
players should be able to interact with the world normally when they are not in claimed chunks

**Comment by cburkey01** [comment]
Yup someone else has reported this, needs to be fixed asap

**Comment by cjburkey01** [comment]
Fixed in https://github.com/cjburkey01/ClaimChunk/commit/b20c9cbff2d6e87f49a9f6d04f5f972e9c406748

Should have 0.0.19 out later tonight
