### ISSUE TITLE
Protect Animals in Claim

### ISSUE THREAD

**Issue by Kaylox** [cjburkey01/ClaimChunk#123]
Animals should not be able to take damage when they are in a claim.
Malicious players kills with bows / potions / fishing rod

**Comment by cjburkey01** [comment]
Woah this took me a lot of time to get to but yeah, entities should be protected within claimed chunks except from the owning player. Just to double check, do you have `protectEntities` set to `true` in the config under the `protection` category?

**Comment by Kaylox** [comment]
Currently in the config, the blockAnimals line is set to true

**Comment by cjburkey01** [comment]
Check on `protectEntities`

**Comment by Kaylox** [comment]
Here is my config.yml : https://prnt.sc/r3x79f

**Comment by cjburkey01** [comment]
What version of ClaimChunk are you using? It looks like you’re missing some options

**Comment by Kaylox** [comment]
J'utilise la 0.0.15 de votre plugin

**Comment by Kaylox** [comment]
I use the 0.0.15 of your plugin

**Comment by cjburkey01** [comment]
Is there something specific you’re avoiding in newer versions?

**Comment by Kaylox** [comment]
I was not aware that a new version was released. Can I still use the old database?

**Comment by cjburkey01** [comment]
Yes, they should be compatible. Let me know if you have any trouble with it

**Comment by Kaylox** [comment]
normal that my ClaimChunk.db is empty?

**Comment by cjburkey01** [comment]
Sorry it's taken so long for me to get back to you, is the plugin working correctly?

**Comment by cjburkey01** [comment]
Should be fixed with https://github.com/cjburkey01/ClaimChunk/issues/130
