### ISSUE TITLE
Permission for Chunk Giving

### ISSUE THREAD

**Issue by Rhayweth** [cjburkey01/ClaimChunk#124]
Make a claimchunk.give permission so people can toggle the option to transfer chunks to eachother.

(This is a bug if you have reached max chunks (say its 10) and starts giving your alt user chunks, then you can claim 10 new chunks and give those away, repeat this and you can claim how much you want)

**Comment by cjburkey01** [comment]
To be clear, when giving is enabled in the config, `claimchunk.give` will be required for players. It *will* be included in the `claimchunk.player` group permission, however, and thus if you wish to use chunk giving for admins only, you will have to assign permissions specifically instead of using the single one. When permissions are disabled in the config, the giving permission will be granted but chunk giving can still be disabled within the config.

**Comment by cjburkey01** [comment]
Also that bug, can players give other players chunks when the receiving player is maxed out on chunks? That should be a separate issue if so.

**Comment by Rhayweth** [comment]
The claimchunk.claim has already chunk giving that is included, thats why I want to have those two perms separately from eachother, since people want to toggle chunk giving off/on. You can always set up permission just with claimchunk.base and claimchunk.claim. The problem is atm that you cant disable chunk giving because there is no option for it.

**Comment by cjburkey01** [comment]
You can disable chunk giving in the config, but it disables it for everyone including admins at the moment.

**Comment by Rhayweth** [comment]
Where is that option? If you want to disable chunk giving you need to disable claiming aswell and then the point of having the plugin is gone.

For claimchunk.player when you have that perm, you will be able to give chunks away.

**Comment by cjburkey01** [comment]
Under `chunks` set `allowChunkGive` to `false` and players won’t be able to use `/chunk give` anymore but the rest of the plugin will function fine.

**Comment by Rhayweth** [comment]
Oh, we didnt noticed that in the config. Then the issue is kinda gone, just the bug but thats like you said another issue.

**Comment by cjburkey01** [comment]
Fixed the bug that allowed players to give a chunk to someone who would end up with more claims than their max in https://github.com/cjburkey01/ClaimChunk/commit/4b8c669e61768fa510ace672f269878ef65c8aa0

**Comment by cjburkey01** [comment]
Removed the config option and added permission `claimchunk.give` in https://github.com/cjburkey01/ClaimChunk/commit/4b8c669e61768fa510ace672f269878ef65c8aa0
