### ISSUE TITLE
Players cannot eat in other players chunks when looking at a block

### ISSUE THREAD

**Issue by vulgarfate** [cjburkey01/ClaimChunk#126]
Apologies for the lengthy title!

Player 1 is chilling in Player 2s chunk-claimed house. Player 1 holds a carrot, potato, any food stuff while facing a block in the wall (stone, wood, etc.) He tries to eat, and the animation starts to play, but an action bar pop up says "You cannot edit blocks in Player 1s chunk" and the animation never finishes - like when you're lagging out due to your Internet.

Understandable - due to right clicking with a hoe, shovel etc can modify grass, but having to find an open area to eat is mildly irritating, and depending on how Player 1 lives, maybe not possible due to cramped conditions.

It's not a big issue by any means, but I thought it'd be worth reporting. Thanks for your work!

**Comment by cjburkey01** [comment]
This does make sense that it's an issue, but I'm not too sure how I'd fix it. Maybe I'd be able to figure out if the player's right click was actually going to do something or not? I'll have to look at the Spigot API a little more in-depth to see how I'd handle this case. I'm on a little break from plugin dev rn for personal reasons but when I get back to it I'll see what I can do about this. Thanks for the report!

**Comment by vulgarfate** [comment]
Thanks for getting back so quickly! I'm no Java dev so sadly I couldn't really recommend anything. I asked a friend who makes plugins and his reply was mainly "Not block on right click, and check where the player clicked, on chest open event. Or a simply open even and block everything, not block any interaction." No clue what it means but hey, I asked and received haha.
Thanks again, and I hope your break is good!

**Comment by cjburkey01** [comment]
I think this should be fixed with https://github.com/cjburkey01/ClaimChunk/issues/130 but I'll make sure to test

**Comment by cjburkey01** [comment]
I'm going to close this because it's been a long time (oops) but we'll see what 0.0.23 looks like (feel free to reopen this if it's broken)
