### ISSUE TITLE
Ranks System page has a typo

### ISSUE THREAD

**Issue by vulgarfate** [cjburkey01/ClaimChunk#127]
Removed the main text because this is super tiny and quick bug that isn't to do with the plugin haha.

On https://github.com/cjburkey01/ClaimChunk/wiki/Ranks-System, the last sentences say:

> Users are put into ranks with the permission `claimchunk.chunk.<RANK NAME>`. For example: `claimchunk.claim.someRandomExampleRank`

The first says `claimchunk.CHUNK.rank`, the second says `claimchunk.CLAIM.rank`

Very tiny but was wondering how I hit the max when I set up and gave myself an admin rank with max 1000 chunks :P 

Sorry to bother you for such a small thing!

(Quick edit to say I had success with `claimchunk.claim.rank`, but only to individuals and not a specific group like default, vip, admin, using LuckPerms. Unsure if intended)

**Comment by cjburkey01** [comment]
Oops thank you, I’ve fixed it
