### ISSUE TITLE
PvP Blocked

### ISSUE THREAD

**Issue by Serial23** [cjburkey01/ClaimChunk#129]
ClaimChunk Version: 0.0.20

Players can't damage other players but i (with all permissions) can do it, in the config.yml there is "blockPvp: false"

**Comment by cjburkey01** [comment]
Are you the owner of the chunk you/they are in?

**Comment by Serial23** [comment]
Yes, pvp is always locked

**Comment by cjburkey01** [comment]
Could I send you a pre-release for 0.0.21 that might or might not fix it? (If it's still a problem)

**Comment by cjburkey01** [comment]
This will be fixed with https://github.com/cjburkey01/ClaimChunk/issues/130, the new system allows full server control over entity & block permissions within claimed & unclaimed chunks
