### ISSUE TITLE
Vanished players still trigger chunk entering notification

### ISSUE THREAD

**Issue by ego-tistical** [cjburkey01/ClaimChunk#132]
Spigot Version: git-Paper-243 (MC: 1.14.4)
ClaimChunk Version: 0.0.15

Plugin Used to Vanish: https://www.spigotmc.org/resources/supervanish-be-invisible.1331/

Vanished players still trigger chunk notification to owner of the chunk.

**To Reproduce**
1. Using plugin to vanish (i.e. SuperVanish)
2. Crossing into owned chunks
3. Owner alerted to vanished players entrance

**Expected behavior**
Vanished players should not trigger the notification to the owner.

**Additional context**
Maybe a perm to be added that bypasses chunk notification could fix this issue

**Comment by cjburkey01** [comment]
Oh they're definitely not supposed to, but I don't know what else on my end I can do to fix that? Right now I'm using the [`canSee()`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#canSee-org.bukkit.entity.Player-) method but if that's not working, I need to figure out how that plugin makes the player invisible so I can detect that.

**Comment by cjburkey01** [comment]
Added `claimchunk.invis` in https://github.com/cjburkey01/ClaimChunk/commit/a2cbd29a520e3dd62fb203b2e3a7ea85de29be36 to bypass sending alerts to chunk owners, it will be released with 0.0.23, thank you! Sorry it took so long!
