### ISSUE TITLE
PlaceholderAPI Support

### ISSUE THREAD

**Issue by TheGamingChris** [cjburkey01/ClaimChunk#134]
**Describe the solution you'd like**
Implement Placeholders like %chunk_owner% to display the current chunk owner

**Comment by KNNI** [comment]
+1

**Comment by cjburkey01** [comment]
This would be a great idea, definitely going to check it out!

**Comment by cjburkey01** [comment]
Finally getting around to this; what I'll do is have a placeholder like `%claimchunk_owner%` which is the owner's username and `%claimchunk_name%` which will be the name of the owner's claimed chunks. Then, I'll also do `%claimchunk_claims%` for the number of claims a player has.

**Comment by cjburkey01** [comment]
Ok, actually, I'll do `%claimchunk_current_owner%` for the  username of the owner of chunk that the player is currently in, `%claimchunk_current_name%` for the display name of the chunk that the player's in, `%claimchunk_my_name%` will show the player's custom chunk name, and finall `%claimchunk_my_claims%` will be the number of claims that this player has.

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/a55b5cdc42f3db7a21a149b9c348750c7c869aa8
