### ISSUE TITLE
First chunk is not free

### ISSUE THREAD

**Issue by mateuszpokojowczyk** [cjburkey01/ClaimChunk#135]
**Versions**
Spigot Version: -
ClaimChunk Version: 0.0.20

**Describe the bug**
If player has enough money, he will be charged for "free" chunk.

**To Reproduce**
1. Enable economy, set price for claim, enable free x claims.
2. Give player who hasn't claimed anything enough money to buy.
3. Claim chunk.

**Expected behavior**
Player should only be charged for paid chunks.

**Solution to implement**
As stated in https://pastebin.com/ZVXhcdsF

**Comment by cjburkey01** [comment]
I'm surprised no one else has mentioned this, I'll double check on my own private test server but that's weird. I have rewritten that code every other release lmao I need to get it set the heck up correctly and leave it alone lol

**Comment by cjburkey01** [comment]
Fixed in https://github.com/cjburkey01/ClaimChunk/commit/d1988791caf46051287f786cdd78321023983eba
