### ISSUE TITLE
blockUnclaimedChunks is preventing players to edit even on disabled worlds

### ISSUE THREAD

**Issue by Zagarwin** [cjburkey01/ClaimChunk#140]
I didn't know if the following was a feature or an actual bug so i flagged it as a request.

I enabled the behavior "blockUnclaimedChunks" in the configuration so the players can't edit a wild chunk if if they didn't claim it first. It's working well but, i have many maps, and this configuration is preventing players from editing on all of them, even if i added them to the "disabledWorlds" list. And yes i am sure the worlds are disabled because the player "Can't claim chunks here" when he tries.

Now i think that this is maybe intended and that this configuration is supposed to apply on claim actions only, but this isn't very convenient

**Comment by cjburkey01** [comment]
That's definitely not intended, thank you for the report!

**Comment by cjburkey01** [comment]
Fixed in https://github.com/cjburkey01/ClaimChunk/commit/90fc2829c1e1972cb206c808126478462ac47dd9
