### ISSUE TITLE
Missing Protections

### ISSUE THREAD

**Issue by Rhayweth** [cjburkey01/ClaimChunk#142]
**Versions**
Spigot Version: 1.15.2
ClaimChunk Version: 0.0.20

**Describe the bug**
1. Creeper can blow up item frames in claimed chunks.
2. Players can shoot arrows at item frames and steal stuff from it when the chunk is claimed.
3. Water and Lava can be placed outside the claim and flow in to destroy crops in claimed chunks.
4. Other people can trade with villagers when the claim is claimed.
5. Armorstands are not protected inside the claim.
6. You can use shears to steal wool from sheeps thats inside a claim.
7. Wither destroys blocks inside a claim if you spawning them in your claim

I guess thats about it. I have tried these with my alt user when I claimed with my main :)

**Comment by cjburkey01** [comment]
This will have to wait until the event system is finished being rewritten for now unfortunately

**Comment by NaokiStark** [comment]
Pistons can push blocks inside the claim

**Comment by cjburkey01** [comment]
Should all be possible to fix with https://github.com/cjburkey01/ClaimChunk/issues/130
