### ISSUE TITLE
UUID unknown 

### ISSUE THREAD

**Issue by Rhayweth** [cjburkey01/ClaimChunk#145]
Spigot Version: Paper 1.15.2
ClaimChunk Version: 0.0.20

**Describe the bug**
When uuid data is corrupted and deleted, and the player whose data is corrupted rejoins, all his/her claims are registered under the name Unknown

**Additional context**
Notch's playerdata file (UUID) gets corrupted or removed entirely. This was unintentional. Zoof.. there goes all Notch's data..
But luckily, me, the server owner made a backup 10 days ago. He might have lost some stuff, but most has been recovered. Problem solved!.. right? 
Aargh! Now all his claims are registered as ''Unknown'', and his property is owned by no one. There goes all his progress.. :(

This is a requested bug from Dancing Walkman#5893 on Discord.

**Comment by cjburkey01** [comment]
Fixed in Discord

**Comment by Rhayweth** [comment]
:D
