### ISSUE TITLE
Per-Chunk Features

### ISSUE THREAD

**Issue by cjburkey01** [cjburkey01/ClaimChunk#147]
**Describe the solution you'd like**
Chunks can have permissions/protections enabled or disabled by the players using commands. This issue takes the place of https://github.com/cjburkey01/ClaimChunk/issues/73 and https://github.com/cjburkey01/ClaimChunk/issues/143

**Comment by JustDoom** [comment]
Would this be something like the /f map command in the factions plugin? Different symbol for claims/non claims and different colour depending who the claim belongs to

**Comment by cjburkey01** [comment]
> Would this be something like the /f map command in the factions plugin? Different symbol for claims/non claims and different colour depending who the claim belongs to

This is pretty much how I want it to be (at least bare minimum so it's configurable while playing and such). In a more perfect world, there would also be a GUI to work with these, but trying to imagine that in my head is a little ugly with the inventory-style GUIs.

**Comment by JustDoom** [comment]
It would appear I somehow sent this in the wrong issue. Meant to be in #107. Sorry about that

Yea a chat based chunk map

**Comment by cjburkey01** [comment]
Will merge in https://github.com/cjburkey01/ClaimChunk/pull/268
