### ISSUE TITLE
Area of Chunks Claimed Outline

### ISSUE THREAD

**Issue by BrandonGamesYT** [cjburkey01/ClaimChunk#149]
**Is your feature request related to a problem? Please describe.**

Not a problem at all currently!

**Describe the solution you'd like**

I would love to see some sort of /chunk view [seconds/minute] or /chunk view (Enable/Disable). Were for when you are around your chunks if you could view the whole radius of your chunks around you that you have claimed.

Pretty much a better way to visualize all the chunks you have claimed in your surrounding area instead of just have /chunk list and trying to read cords!

Thanks!

**Comment by cjburkey01** [comment]
Currently `/chunk show` is all there is at the moment. A map command is planned but I suppose a better outline idea would make sense

**Comment by cjburkey01** [comment]
Finally added as of 0.0.23-prev9 in commit https://github.com/cjburkey01/ClaimChunk/commit/1c4ee46f081f9ac787148c3d071736cba3816cce
