### ISSUE TITLE
Display the max chunks you can claim 

### ISSUE THREAD

**Issue by WizWazWizard** [cjburkey01/ClaimChunk#155]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cjburkey01** [comment]
Added `claimchunk_my_max_claims` in https://github.com/cjburkey01/ClaimChunk/commit/97d69ef47104b0d8afdddfed8f29b5501b170dc2
