### ISSUE TITLE
PvP blocked in claimchunk

### ISSUE THREAD

**Issue by mapacheee** [cjburkey01/ClaimChunk#156]
**Versions**
Spigot 1.16.1
ClaimChunk Version: 0.22

**Describe the bug**
I have set the BlockPvp in false and still cannot pvp within the claims

**Expected behavior**
That can be pvp within the Claims.

srry my english :(

**Comment by cjburkey01** [comment]
Should be fixed in https://github.com/cjburkey01/ClaimChunk/issues/130
