### ISSUE TITLE
make impossible you can't make /sethome in a claim where you don't have access with Essentials Home

### ISSUE THREAD

**Issue by Sayrix** [cjburkey01/ClaimChunk#159]
I get frustrated when someone can put a home in my claims when I haven't given them access to my claim.
So I propose that we can't put a home in when we don't have access to the claim.

**Comment by cjburkey01** [comment]
Now, there isn’t a *perfect* solution for this, but! we do have the ability to disable certain commands within claimed chunks for people without access. The system is currently being rewritten, so i can’t remember if it will also block chunk owners from using it, but if you edit your config to have this:
```
blockedCmds:
- 'sethome'
```
You can read more about that here: https://github.com/cjburkey01/ClaimChunk/wiki/Configuration-File#protection-settings

Hope this solves your problem! Let me know if you need anything else
