### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by DeathsGun** [cjburkey01/ClaimChunk#16]
The following improvements would be good:
1. JSON instead of self parsing use Gson
2. SQL support

**Comment by cjburkey01** [comment]
I'll go ahead and implement the Gson support, possibly SQL if I'm not feeling lazy.

**Comment by cjburkey01** [comment]
Json support has been added.

**Comment by NexAdn** [comment]
What's the state of SQL support atm? I'd really love to see SQL support being implemented soon.

**Comment by cjburkey01** [comment]
Update: This is actually going to be a rewrite of the backing data API but that would make it _so_ much easier to get MySQL support going, I'll start working on this for 0.0.13.

**Comment by cjburkey01** [comment]
MySQL support has been added and is effectively finished as of https://github.com/cjburkey01/ClaimChunk/commit/f86978da7023d9c3b7fe31cd0ebf77f5cb153a84
