### ISSUE TITLE
Only allow certain amount of chest to be placed inside claim

### ISSUE THREAD

**Issue by DeanMSalter** [cjburkey01/ClaimChunk#160]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Only allow players to place a configurable amount of chests in a claim/claims.

**Describe alternatives you've considered**
No real option that would hook into this plugin other than manual inspection.

**Additional context**
NA

**Comment by cjburkey01** [comment]
I'll go ahead and close this only because 0.1.0 is getting closer, with a more settled API an addon could be made for this kind of purpose.
