### ISSUE TITLE
Fix MySQL Player Names Returning Null

### ISSUE THREAD

**Issue by cjburkey01** [cjburkey01/ClaimChunk#161]
**Describe the bug**
Courtesy of ChronicSquid on the Discord:
![Discord chat with ChronicSquid](https://user-images.githubusercontent.com/9255643/97070993-dbbaad00-15aa-11eb-8082-3c5550f96e33.png)

*Transcription:*
"Exiting Entering unclaimed territory's base"
My friend claims a chunk but it's throwing the "unknownChunkOwner" messages
Or what is causing it to not know who is owning chunks?
We're using MySQL, so could it be a delay deal with that?

**Comment by ChronicSquid13** [comment]
Thank you!

**Comment by cjburkey01** [comment]
Turns out it was something with the way I was writing the names, should be fixed in f2d9ff032ffbe3be95a4139c4664e0310e6063cb and released with 0.0.23
