### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ETechTechnologies** [cjburkey01/ClaimChunk#163]
I would like it if you could set player specific chunk limits, so a default of 25 but you can give specific players more or unlimited chunks. 

Also maybe a permission that grants the ability to claim unlimited chunks without having access to the admin commands.

**Comment by ChronicSquid13** [comment]
You could use the Rank system to allow specific ranks more claims, and for the unlimited, you could make it so that a rank called "Unlimited Claims" could have a node for like.. 10000 allowed claims

**Comment by cjburkey01** [comment]
For now I'll have to second the suggestion to use [the ranks system](https://github.com/cjburkey01/ClaimChunk/wiki/Ranks-System); there may, however, be a new way of doing it as per https://github.com/cjburkey01/ClaimChunk/issues/164 in future updates (likely *not* 0.0.23 unfortunately).

**Comment by cjburkey01** [comment]
(I'm going to close this one, you can follow that issue linked above or reopen this if you'd like)
