### ISSUE TITLE
Don´t use getCurrencyInstance

### ISSUE THREAD

**Issue by Cenorida** [cjburkey01/ClaimChunk#166]
**Versions**
Spigot Version: Latest
ClaimChunk Version: Latest

**Describe the bug**
In some countries, the currency in the message is bugged or look weird when claim or unclaim a non-free chunk and sometimes, the symbol of the currency in the message does not match the symbol in the used economy-plugin.

**Comment by cjburkey01** [comment]
Will update thank you!

**Comment by cjburkey01** [comment]
Fixed in https://github.com/cjburkey01/ClaimChunk/commit/fa2e98a1a6f83b58bb6c0ef49f02106fb6cdb694 (will be released with 0.0.23)
