### ISSUE TITLE
Particle type not updating when using /chunk reload

### ISSUE THREAD

**Issue by AlonsoUrmeneta** [cjburkey01/ClaimChunk#188]
**Versions**
Spigot Version: git-Paper-545 (MC: 1.16.5) Api version 1.16.5-R0.1-SNAPSHOT
ClaimChunk Version: 0.0.22

**Describe the bug**
When you change the particle type in config.yml and use the command /chunk reload, the particle type doesn't update until a server restart.

**To Reproduce**
1. Change the particle type in config.yml
2. Use the command /chunk reload

**Expected behavior**
I expected the new particle set in the config to show up after doing /chunk reload

**Comment by cjburkey01** [comment]
Ah, I suspect this has to do with the `/chunk reload` being slightly broken in versions 0.0.22. For now, if you reload the entire server (or perform a full reboot), does the particle type at least update to the correct kind?

**Comment by cjburkey01** [comment]
I'm going to close this issue because it should be fixed in 0.0.23–to be released soon(tm)–feel free to reopen this issue if it's broken again
