### ISSUE TITLE
permission bug

### ISSUE THREAD

**Issue by uisufian** [cjburkey01/ClaimChunk#21]
https://postimg.org/image/jzkf8hrmd/

PermissionsEx add all the permission for default user its not working , 
other plugins given permission works fine its only happens with this plugin

spigot version 1.12 latest

only work for op

**Comment by DeathsGun** [comment]
You need the permission `claimchunk.base` to use `/chunk`
The subcommands have own permissions

**Comment by uisufian** [comment]
https://pastebin.com/CQTBEHY7

chunk price is set but still can can buy new chunk for free
https://s26.postimg.org/6bnt3nc49/screenshot_104.png

**Comment by cooldany** [comment]
on the version 1.12.2

**Comment by cjburkey01** [comment]
Do you still have this issue? If so, does deleting the config and letting it regenerate fix it?

**Comment by cjburkey01** [comment]
I'm going to close this; if you're still experiencing it, feel free to reopen it.
