### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by cjburkey01** [cjburkey01/ClaimChunk#212]
Noting the switch from Git's default branch name of "master" to "main" (last year), I figure it's time to update ClaimChunk to the new standard. If no one has any qualms with this, I'll go ahead and make this change in a few days. Compatibiltity shouldn't be affected, though there's always the chance someone needs the main branch to be named the same thing.
Given the small nature of ClaimChunk's developer base, however, I feel this change should affect few–to no–other people.

**Comment by Geolykt** [comment]
I myself do not care about changing the default branch
