### ISSUE TITLE
plugin.yml incorrect

### ISSUE THREAD

**Issue by ErythroCraft** [cjburkey01/ClaimChunk#226]
Hi

I'm using your plugin and was wondering about the latest download of 0.0.22

Please watch out your plugin.yml, because it contains a version misstake on line 8

![Bild_2021-12-01_171608](https://user-images.githubusercontent.com/76217862/144271263-5ec76432-3a7b-4ac2-8178-22e5138521b1.png)

**Comment by ErythroCraft** [comment]
You can simple fix this by creating a new version 0.0.23

**Comment by Geolykt** [comment]
https://github.com/cjburkey01/ClaimChunk/blob/main/src/main/resources/plugin.yml#L8 this error will not be performed anytime soon. And there won't be a .23 for some time since the update went a bit too large

**Comment by ErythroCraft** [comment]
Pefect and Thanks.
