### ISSUE TITLE
Claim Chunk Plugin Not Working Properly

### ISSUE THREAD

**Issue by Crazy6406** [cjburkey01/ClaimChunk#228]
**1.16**
Spigot Version:
ClaimChunk Version:

**its not downloading like folders in server**
its not downloading like folders in server. 

**Expected behavior**

**Additional context**

**Comment by Geolykt** [comment]
You provided next to no information, and the information you provided is nonsensical to me. It would be best if you were to try to reword it as well as attach more concise information on expected and actual behaviour.

Claimchunks shouldn't download anything, so I'm a bit confused
