### ISSUE TITLE
Entering chunk without custom name

### ISSUE THREAD

**Issue by Red3Tango** [cjburkey01/ClaimChunk#23]
When entering a chunk that is owned by another player, that has not set a custom name, nothing is displayed.
https://github.com/cjburkey01/ClaimChunk/blob/4b78e4be0b3379958b8a94ee183020dd1f874f21/src/main/java/com/cjburkey/claimchunk/event/PlayerMovementHandler.java#L54
I believe this should be the correct code.
`String newName = (nh.hasChunkName(newOwner)) ? nh.getChunkName(newOwner) : nh.getUsername(newOwner); `

**Comment by cjburkey01** [comment]
Yes, that does appear to be an error on my part. Thank you, I probably wouldn't have found the error if you hadn't pointed it out.
