### ISSUE TITLE
Admin Permissions Not Working?

### ISSUE THREAD

**Issue by meowsome** [cjburkey01/ClaimChunk#231]
**Versions**
Spigot Version: Paper 1.18.1-97
ClaimChunk Version: 0.0.23-RC3

**Describe the bug**
Admins and OPs can't edit the chunks of other players, open chests, open doors, break blocks, etc. They can't interact with others chunks at all. I tried permissions `claimchunk.admin`, `claimchunk.*`, and as an OP.

**To Reproduce**

1. Give yourself permission `claimchunk.admin`
2. Try editing another player's chunk.
3. Get an error message saying you can't interact with this person's chunk

OR:

1. Give yourself op
2. Try editing another player's chunk
3. Get an error message saying you can't interact with this person's chunk

**Expected behavior**
With the permission or OP, in previous versions, I was able to edit the chunks of other players, including everything mentioned above. 

**Additional context**
N/A

**Comment by cjburkey01** [comment]
Does `/chunk admin override` work for you? It should toggle (ideally)

**Comment by meowsome** [comment]
That works, my apologies, I didn't know about this command. Do I have to run this every time I join, or every time the server restarts, or something? Or do I always have admin override when toggled on?

**Comment by cjburkey01** [comment]
It should only reset when the server restarts, rejoining without a server reboot might keep you in the list so should keep? Can't be certain but let me know if you find anything else you don't expect.
