### ISSUE TITLE
Random boolean on "/chunk unclaim all"

### ISSUE THREAD

**Issue by ghost** [cjburkey01/ClaimChunk#240]
**Versions**
Spigot Version: Purpur 1.18.1
ClaimChunk Version: 0.0.23-RC7

**Describe the bug**
When i write /chunk unclaim all, the plugin suggest me "true" and "false"

**To Reproduce**
1. Write /chunk unclaim all (IMPORTANT: don't tab the word "all", you must write "all" letter by letter)
2. You will see the plugin will suggest you "true" and "false"

**Expected behavior**
I expect when i write /chunk unclaim all, there aren't other suggestion. 

![photo_2022-03-12_12-56-09](https://user-images.githubusercontent.com/43071315/158017052-02fb4b07-244b-4f46-8557-363a0b2016ff.jpg)

### **I tried to replace "true" and "false" with "" in messages.json, but there is a little space suggestion too**
![lmao](https://user-images.githubusercontent.com/43071315/158017073-b06ad737-bda6-4879-8e23-e9d76f96ea03.jpg)

**Comment by cjburkey01** [comment]
Ah, the reason is that you can write `/chunk unclaim all <EVERY WORLD? true/false>` so it's showing that for you (I think?)

**Comment by cjburkey01** [comment]
Probably fixed with the new command system (https://github.com/cjburkey01/ClaimChunk/projects/3)
