### ISSUE TITLE
Disallow spawn claim / worldguard region claim

### ISSUE THREAD

**Issue by AIO-Develope** [cjburkey01/ClaimChunk#245]
Is there any way that Player cant claim spawn areas or worldguard regions?

**Comment by cjburkey01** [comment]
Yep! Here's the wiki page: https://github.com/cjburkey01/ClaimChunk/wiki/WorldGuard-Integration

Basically, you can set the `chunk-claim` to `DENY` where you don't want players to be able to claim.
