### ISSUE TITLE
Players allowed to place water in a claim with a Bucket of Pufferfish

### ISSUE THREAD

**Issue by cj1705** [cjburkey01/ClaimChunk#247]
**Versions**
Spigot Version: 1.18.2 (Paper)
ClaimChunk Version: 0.023-rc7

**Describe the bug**
A player is allowed to place down a Bucket of Pufferfish in a claimed chunk and is able to flood the claim. Regular lava and water are protected normally.

**To Reproduce**

1. Get a Bucket of Pufferfish
2. Place it down within a claim

**Expected behavior**
The water to not be able to spawn and flood a claim.

**Additional context**

A short clip of the issue.

https://user-images.githubusercontent.com/58826886/165177714-0c1ea37c-3d26-4728-aef4-cbc6b8e43015.mp4

**Comment by cjburkey01** [comment]
Please reply if this issue still exists, it's been 2 years :P
