### ISSUE TITLE
Set More Specific Permissions

### ISSUE THREAD

**Issue by starcrasher87** [cjburkey01/ClaimChunk#25]
Add more options for what players may do on claimed chunks. For example...
chests contents: 0 = no interaction, 1 = view, 2 = add, 3 = remove
other item inventories: 0 = no interaction, 1 = view, 2 = add, 3 = remove
Minecarts/boats that the chunk owner placed: 0 = no interaction, 1= Mount/dismount, 2 = move
operate redstone components like switches, levers, buttons, tripwires, etc: true, false
Open/close doors: true, false
PvP: true, false
place projectiles into item inventories(to prevent using dispensers for PvP damage): true, false
place tnt blocks: true, false
place tnt into item inventories(to prevent using dispensers for griefing): true, false

Also allow ops to set global defaults for what protections are active for newly claimed chunks. Unprivileged users should then be given the option to set their own personal defaults for all future claims. Furthermore, permissions should be editable on individual chunks after claiming, or optionally update all claimed chunks. Ops should be able to set which permissions are editable by unprivileged users, so certain permissions are always set to the global default.

**Comment by starcrasher87** [comment]
Also note, players are unable to exit the building that I built to protect the spawn area from mobs, because this mod will not allow them to open the steel doors using pressure plates. Setting permissions for doors and redstone components would solve this issue.

**Comment by cjburkey01** [comment]
This mod really wasn't developed for the purpose of spawn-protecting and that sort of thing. If you're looking for something to do that, I'd recommend [WorldGuard](https://dev.bukkit.org/projects/worldguard), which allows you to get pretty specific with what permissions to allow and deny. Adding permissions to this plugin wouldn't be _insanely_ difficult, but it would be, for the most part, unnecessary to the average user.
