### ISSUE TITLE
Giving players chunks as a reward

### ISSUE THREAD

**Issue by pnd0** [cjburkey01/ClaimChunk#251]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem

**Describe the solution you'd like**
So I want players to be able to get maybe 1-5 chunks every hour that they play so that they're not just stuck with their rank's limited amount of claims

**Describe alternatives you've considered**
I've considered making duplicated permissions that just have more chunks but it seems like a silly idea and may not work as well

**Comment by cjburkey01** [comment]
Will finally be (sort of) supported in 0.0.24 with each player having an "extra" number of chunks they can claim, which can be controlled via admin set/give/take commands. You'd be able to set some automatic command sender plugin to automatically execute the give extra chunk claims command. The existing roles system will still exist, the extra chunks will be added on top of the default in the config/assigned player role via permission.
