### ISSUE TITLE
[Question] How to undone /chunk access <player> ?

### ISSUE THREAD

**Issue by ExDomino** [cjburkey01/ClaimChunk#26]
Hello,

After use of the command `/chunk access <player>`,
...how to deny this player ? There is no `/chunk deny <player>` or somthing like that?

Thank in advance.

Edit : And how to see the list of access players?
`/chunk access` alone could print your "friend" list.

**Comment by cjburkey01** [comment]
Just run the same command, it toggles the player’s access.
