### ISSUE TITLE
Single command claiming

### ISSUE THREAD

**Issue by assada** [cjburkey01/ClaimChunk#271]
**Describe the solution you'd like**
For players command usages sometimes are complicated. So, while the GUIwill not appear soon, I propose to add a single command for claiming. More on video.

https://youtu.be/VvX5A2-TbZI

Unfortunately, I don't have much time to finish the code (to "production-ready" condition) =(
![image](https://user-images.githubusercontent.com/1472664/197341523-554df4d3-7bf0-4421-9f68-bf010ac1f043.png)

**Comment by Geolykt** [comment]
Would still be good if you were to push your partly-done code to some repository so we have a bigger clue on what you are attempting to achieve and can thus help you further there

**Comment by assada** [comment]
@Geolykt check PR https://github.com/cjburkey01/ClaimChunk/pull/272
