### ISSUE TITLE
Fix Dynmap claim names

### ISSUE THREAD

**Issue by woliver99** [cjburkey01/ClaimChunk#273]
I have no clue if you guys have the source code of the Dynmap addon but if you guys do il gladly try fixing it. I like chunk claim i just need to fix the Dynmap name of claim and have different color for everyone

**Comment by cjburkey01** [comment]
I wish I did, but I don't and the repo owner (as I bet you found out yourself) deleted their account :/

I think your best bet would be decompiling the plug-in and doing your best to decipher what happens but I'm not sure how involved that would be. To be honest, ClaimChunk is also in dire need of a better public API that would make implementing that plug-in much easier.

I tried in the past and maybe I will in the future, but for the time being I barely have enough time to work on fixes for my own code :(
