### ISSUE TITLE
Number of chunks & ADMIN privileges

### ISSUE THREAD

**Issue by excaliburkim** [cjburkey01/ClaimChunk#275]
Thank you for making this program.
I am using it very well.

I would like to request 2 features from you.
1. A command that allows each user to check their [used chunks/total chunks]
2. I want someone with ADMIN privileges to be able to open all boxes and break blocks when entering each user's area.

**Comment by cjburkey01** [comment]
I'll close this issue as the `/chunk admin` command answers the second point, similar to the factions admin override feature. That first point does need to be added, probably to the `/chunk list` command
