### ISSUE TITLE
Placeholders do not work

### ISSUE THREAD

**Issue by NoLifePenguin** [cjburkey01/ClaimChunk#287]
**Versions**
Spigot Version: 1.12.2
ClaimChunk Version: 0.0.23-RC7

**Describe the bug**
You described that placeholders work, but they do not.

**To Reproduce**
1. Install the recent plugin, try to use the placeholder

**Expected behavior**
There to be a valid placeholder

**Additional context**
N-A

**Comment by cjburkey01** [comment]
Hm, if you're using 1.12 you may want to downgrade to an older version of ClaimChunk, does 0.0.22 work? here's the release page: https://github.com/cjburkey01/ClaimChunk/releases/tag/0.0.22  I'm not 100% sure that'll be old enough though, that build is from the 1.16 days
