### ISSUE TITLE
Player are able to use redstone stuff in other's chunks

### ISSUE THREAD

**Issue by gabgat** [cjburkey01/ClaimChunk#288]
**Versions**
Paper Version: 1.20.2 - 234
ClaimChunk Version: 0.0.24-RC1 (I build it) / 0.0.23-RC8

**Describe the bug**
Players are able to use buttons, pressure plates, and everything that uses Redstone, in other's chunks (claimed)

**Additional context**
That's my config:
basic:
  disablePermissions: false
  checkForUpdates: true
log:
  debugSpam: false
  anonymousMetrics: true
titles:
  useTitlesInsteadOfChat: true
  useActionBar: true
  titleFadeInTime: 20
  titleStayTime: 140
  titleFadeOutTime: 20
  chunkEnterExitSpamDelay: 20
colors:
  infoColor: GOLD
  errorColor: RED
chunks:
  maxChunksClaimed: 2
  particlesWhenClaiming: true
  hideAlertsForVanishedPlayers: true
  automaticUnclaimSeconds: -1
  unclaimCheckIntervalTicks: 1200
  displayNameOfOwner: true
  defaultSendAlertsToOwner: true
  maxPerListPage: 5
  disabledWorlds: []
  nearChunkSearch: 5
  # Anything higher than 25 runs the risk of crashing your server
  maxScanRange: 20
chunkOutline:
  name: SMOKE_LARGE
  durationSeconds: 5
  spawnsPerSecond: 2
  particlesPerSpawn: 2
  heightRadius: 3
protection:
  blockUnclaimedChunks: false
  blockPlayerChanges: true
  blockInteractions: true
  blockTnt: true
  blockCreeper: true
  blockWither: true
  protectEntities: true
  blockPvp: false
  blockedCmds: []
  disableOfflineProtect: false
worldguard:
  allowClaimsInRegionsByDefault: false
  allowClaimingInNonGuardedWorlds: true
  allowAdminOverride: true
economy:
  useEconomy: true
  claimPrice: 1000.0
  unclaimReward: 100.0
  firstFreeChunks: 0
data:
  saveDataIntervalInMinutes: 10
  keepJsonBackups: true
  minBackupIntervalInMinutes: 120
  deleteOldBackupsAfterMinutes: 10080
database:
  useDatabase: false
  groupRequests: true
  convertOldData: true
  hostname: 127.0.0.1
  port: 3306
  database: MyServer
  username: root
  password: root
  printDebug: false
  useSsl: false
  allowPublicKeyRetrieval: false
floodclaim:
  enabled: true
  maximumIterations: 6
  maximumArea: 41

I don't know why, but this part: "
protection:
  blockUnclaimedChunks: false
  blockPlayerChanges: true
  blockInteractions: true
  blockTnt: true
  blockCreeper: true
  blockWither: true
  protectEntities: true
  blockPvp: false
  blockedCmds: []
  disableOfflineProtect: false
"
wasn't there, i added it from your config example inside the wiki. The plugin did not generate it (both 0.0.24 and 0.0.23)

**Comment by cjburkey01** [comment]
Hi there, I know documentation for the recent versions of ClaimChunk is, uh, very lacking to say the least, but in 0.0.23 that section of the config isn't used anymore.

The new way to customize the permissions (and I don't love this solution, believe me, I want to change it all again) is to go into the `/plugins/ClaimChunk/worlds/` folder and edit each of the worlds you'd like to customize, each file contains an explanation of how to modify the file at the top. So to disable redstone interaction, scroll to the bottom of the file and look for the section that looks like this: 

```
claimedChunks.blockAccesses:
  @CONTAINER  B:false P:false I:false E:false ;
  @DOOR  B:false P:false I:false E:false ;
  @REDSTONE  B:false P:false I:true E:false ;
  __DEFAULT__  B:false P:false I:false E:false ;
```

On the line that says `@REDSTONE  B:false P:false I:true E:false ;` you should change `I:true` to `I:false`

So do that in each world you'd like redstone protecting in players' claimed chunks.

Slightly unrelated, but if you don't want players claiming chunks in a certain world, you can set `enabled  true ;` to `enabled  false; ` in this section near the top of the file:

```
_:
  enabled  true ;
  preventAdjacent  [ TRAPPED_CHEST, CHEST ] ;
  preventPearlFromClaims  false ;
  protectOffline  true ;
  protectOnline  true ;
```

Some options are more self-explanatory than others, so I'll leave this issue open unless you get it figured out 👍

**Comment by gabgat** [comment]
Thaks! Seems to work now, closing the issue
