### ISSUE TITLE
disabledWorlds Bug? 1.20.2

### ISSUE THREAD

**Issue by JustKing009** [cjburkey01/ClaimChunk#289]
**Versions**
Spigot Version: purpur-1.20.2-2084
ClaimChunk Version: 0.0.23-RC7

**Describe the bug**
In the Config.yml, the "disabledWorlds" setting has no effect.
I have written that in the config, but it doesn't make any difference.
disabledWorlds:
  - Farmwelt
  - world_nether
  - world_the_end

**Expected behavior**
I'm glad to hear that it helped in deactivating the worlds for claiming.

**Comment by assada** [comment]
looks like some issue in here: https://github.com/cjburkey01/ClaimChunk/blob/main/src/main/java/com/cjburkey/claimchunk/service/prereq/claim/WorldPrereq.java#L18

@cjburkey01 can you please help with this?

**Comment by cjburkey01** [comment]
Oops sorry it took me a bit to reply but with 0.0.23 you can disable a world by opening the text file for the world in the `plugins/ClaimChunk/worlds` folder (each file is the name of a world). There's a big chunk of text at the top of each world file and after that, there should be a section called `_:` with an `enabled` option, which you can set to false. I know it's confusing, there's a couple years of moving stuff around :p

**Comment by cjburkey01** [comment]
I believe I can mark this as closed, though in the future there will be an admin command to enable/disable ClaimChunk in given worlds.
