### ISSUE TITLE
WorldGuard Support

### ISSUE THREAD

**Issue by Matthysse** [cjburkey01/ClaimChunk#30]
Add WorldGuard support, we can't claim chunk with min 1 block of an worldguard region in, and whitelist and blacklist regions, for example, i CAN'T claim in region "City" but i CAN in region "Jungle"

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/060f79f3184c0f9986d7c7edc5c2db817e6adf60

The flag `chunk-claim` is `ALLOW` by default, it must be set to `DENY` to prevent claiming of the chunks touching that region.
