### ISSUE TITLE
error messages in console

### ISSUE THREAD

**Issue by timmyb4** [cjburkey01/ClaimChunk#301]
**Versions**
Spigot Version: 1.21
ClaimChunk Version: 0.0.25-FIX3

**Describe the bug**
Random Error messages in console.

**To Reproduce**
1. Run server.
2.Error are  Random placed in the console.

**Expected behavior**
No errors in the console

**Additional context**
- [ma 15:10:34 ERROR Minecraft] [ClaimChunk] Failed to get entity by name "MUSHROOM_COW"
- [ma 15:10:34 ERROR Minecraft] [ClaimChunk] Failed to get entity by name "LEASH_HITCH"
- [ma 15:10:34 ERROR Minecraft] [ClaimChunk] Failed to get entity by name "MINECART_HOPPER"
 
- [ma 15:10:34 ERROR Minecraft] [ClaimChunk] Failed to get entity by name "MINECART_MOB_SPAWNER"
- [ma 15:10:34 ERROR Minecraft] [ClaimChunk] Failed to get entity by name "MINECART_FURNACE"
- [ma 15:10:34 ERROR Minecraft] [ClaimChunk] Failed to get entity by name "MINECART_TNT"
- [ma 15:10:34 ERROR Minecraft] [ClaimChunk] Failed to get entity by name "MINECART_CHEST"
- [ma 15:10:34 ERROR Minecraft] [ClaimChunk] Failed to get entity by name "MINECART_COMMAND"

**Comment by cjburkey01** [comment]
uh oh, yeeah they changed to using the namespaced names instead of the Material enum names, so I should try to fix that. I wonder why I haven't seen it? Let me try on latest Spigot

**Comment by cjburkey01** [comment]
Wait! Is there a `enum-compatibility-mode` option in your `bukkit.yml` file? If so, try setting it to `true` to see if that works? Those entities changed classes recently, oops

**Comment by cjburkey01** [comment]
> I dont have that option
> 
> 

Hmm, it should be up at the top under the `compatibility` section? It appeared once I updated my test server to 1.21 and restarted it. You're just using Spigot correct, not Paper?

If you haven't customized your bukkit.yml, you could try deleting it and letting it regenerate and see if it appears. I'll need to update my plugin but I don't want to break pre-1.21 yet :p

**Comment by timmyb4** [comment]
I use paper.

**Comment by cjburkey01** [comment]
Ahh, okay, maybe they didn't add that option, I need to update ClaimChunk soon then

**Comment by timmyb4** [comment]
The dit it maybe not because it is not for production servers.

**Comment by cjburkey01** [comment]
> The dit it maybe not because it is not for production servers.

Ok, so I believe the solution would be to rename all the entities within the world profiles located in the `plugins/ClaimChunk/worlds` folder

**Comment by cjburkey01** [comment]
Something that just worked for me is renaming the old world profiles (or the world profile folder) and letting it regenerate. I believe Minecraft/Spigot API changed the names of some of the variants in the code so they wouldn't be recognized if you upgrade from pre-1.21.

* `MUSHROOM_COW` -> `MOOSHROOM`
* `LEASH_HITCH` -> `LEASH_KNOT`
* Minecart names changed from `MINECART_<yada>` to `<yada>_MINECART`

So you can also just rename them in your old config files under the `_._@E_:` section (I'm sorry for that name)
