### ISSUE TITLE
Protect unclaimed

### ISSUE THREAD

**Issue by lazyheadz** [cjburkey01/ClaimChunk#31]
Can you add a feature that protects the unclaimed territory. So, the unclaimed chunks are protected from breaking blocks, and people can break blocks there after claiming a chunk.

**Comment by cjburkey01** [comment]
So, essentially unclaimed chunks are protected from everyone, while claimed chunks are protected as usual? That would be possible

**Comment by lazyheadz** [comment]
That would be awesome if you could add that as an option in the config, for example _(ProtectUnclaimed=true/false)_ :D
