### ISSUE TITLE
Error at Unclaim

### ISSUE THREAD

**Issue by Gobli989** [cjburkey01/ClaimChunk#32]
Hey, I really love your plugin, it's perfect for my server.
But i am having a bit of trouble doing the unclaim. I am getting this error.

https://pastebin.com/sazpWQyb

Please fix it, I really want to use your plugin.

**Comment by NexAdn** [comment]
I experience this bug, too.

**Comment by cjburkey01** [comment]
I've done some work and I don't think I experience it, at least as of commit https://github.com/cjburkey01/ClaimChunk/commit/7f731f55b3ddcc34097f5f5c9cbb2ff8e4cd23d1

I'll try to push this new version after I make sure it still works with 1.12, I updated the particle code so we'll see.

**Comment by cjburkey01** [comment]
Do you experience this with version 0.0.6? If not, I’ll go ahead and close the issue

**Comment by cjburkey01** [comment]
(I’ll reopen it if you still have the problem)
