### ISSUE TITLE
Admin permission not working

### ISSUE THREAD

**Issue by Ytnoos** [cjburkey01/ClaimChunk#33]
If you have chunkclaim.admin or chunkclaim.* you can't still build or unclaim a chunk that is not yours.

**Comment by cjburkey01** [comment]
Have you made sure to give them `chunkclaim.base`? I'll double check the code later, but supposedly I wrote that you'd need both [on the wiki](https://github.com/cjburkey01/ClaimChunk/wiki/Command-and-Permission-Reference). Also, I don't believe `chunkclaim.*` will actually do anything

**Comment by cjburkey01** [comment]
It looks good here, at least the permission is being checked: [in the chunk helper](https://github.com/cjburkey01/ClaimChunk/blob/a8ae86414a9254be3667c85fcb56db8daf775a85/src/main/java/com/cjburkey/claimchunk/ChunkHelper.java#L18). Have you tried disabling all other plugins and seeing if the problem still occurs? Also, were there any errors in the console?

**Comment by Ytnoos** [comment]
![image](https://user-images.githubusercontent.com/21027982/55935626-54aa1c00-5c34-11e9-98b9-5d5a16a2f777.png)

I'm also OP in the server, there are only LuckPerms and ClaimChunk.

**Comment by Ytnoos** [comment]
Well, the real permission is not "chunkclaim" but "claiimchunk"...

By the way, it still doesn't work, I have only 2 plugins: LuckPerms and ClaimChunk

![image](https://user-images.githubusercontent.com/21027982/55935956-3133a100-5c35-11e9-95d0-becf11962ac1.png)

**Comment by cjburkey01** [comment]
Where is it `claiimchunk`?

**Comment by Ytnoos** [comment]
sorry, a typo... You wrote "chunkclaim.base" instead of "claimchunk.base"

**Comment by cjburkey01** [comment]
Oh, sorry, I'll see if I can figure this out. Could you test a different permissions plugin? If you won't want to, I can but It'll be a few hours before I can. I think I tested with bPermissions back when I made the plugin, but I can't remember lol

**Comment by Ytnoos** [comment]
I already tested it with PermissionsEX, nothing to do. By the way don't worry, you have all the time you need.

**Comment by cjburkey01** [comment]
Could you test with the new 0.0.6 release? https://github.com/cjburkey01/ClaimChunk/releases/tag/0.0.6

**Comment by Ytnoos** [comment]
Still nothing, I can't interact with blocks and I can't unclaim chunks, with permissions.

**Comment by cjburkey01** [comment]
Hm, that is definitely strange. I'll have to get a friend to test it with me later. And there definitely aren't any console errors?

**Comment by Ytnoos** [comment]
You could simply edit the chunk owner uuid with a random one and test with just an account. That claim won't be yours.

**Comment by cjburkey01** [comment]
Haha fair point hang on

**Comment by cjburkey01** [comment]
Yeah, it's working as expected for me. I can't edit other's chunks until I give myself the `claimchunk.admin` permission. Which version of Spigot are you running?

![Screenshot_4](https://user-images.githubusercontent.com/9255643/56072350-bddc7d00-5d63-11e9-91b6-24987deed945.png)

**Comment by Ytnoos** [comment]
I think I have some neurological problem... I forgot to remove old ClaimChunk version and the `0.0.6` wasn't loading. Now it works correctly, thank you so much for the update and the help.

**Comment by cjburkey01** [comment]
No problem! Glad to hear it’s working. If you run across anything else, don’t hesitate to file another report 🙂
