### ISSUE TITLE
Faction-like?

### ISSUE THREAD

**Issue by MrmaximoExcssum** [cjburkey01/ClaimChunk#34]
This is about the claim plugin version 6.
For the first I would love if this plugin had a command named /gr where you could add players to your group, everyone you have added to that group can edit your chunks. And when you leaves a chunk i would like if it says forexample "Your left %playername% territorium"
And it would be cool if you also could edit custom colors and have the texts display in Action bar and title and chat. This plugin should be able to if you had a scorebord plugin it could display how many claims you own and how many players is in your group

**Comment by cjburkey01** [comment]
I'm still a little confused about what you're asking for. If you want players to be able to interact with chunks you've claimed, you can use `/chunk access`. You may change the name displayed when someone enters your chunks using the command `/chunk name <DISPLAY NAME>`. Notices on exiting chunks currently only say "Entering unclaimed territory" but that could be changed.

**Comment by MrmaximoExcssum** [comment]
Can you please us discord for support? I wanna help you with this plugin so i made a discord server for you 
there is the invite link    https://discord.gg/zGYrqcq
Put that link on you Plugin site so they can contact there

**Comment by cjburkey01** [comment]
* Allow usage of `/chunk access` to list all players with access to your chunks
* Maybe allow multiple usernames at once to give or retract access?

**Comment by cjburkey01** [comment]
https://github.com/cjburkey01/ClaimChunk/commit/d77153fb4c5cbe54f7b79693e4015b41bd492e5b may have done it, I'll reopen this if you feel it needs more work
