### ISSUE TITLE
Economy is true, but claims don't cost any money

### ISSUE THREAD

**Issue by Teomaniaforreal** [cjburkey01/ClaimChunk#36]
**### Config:**
economy:
  useEconomy: true
  claimPrice: 1500.0
  unclaimReward: 100.0
  firstFree: false
**### version:** 
0.0.6

Users are able to claim chunks without it costing any money.

**Comment by cjburkey01** [comment]
Are there any console errors when ClaimChunk loads? If not, does it say anywhere that the economy support was successfully enabled? Finally, if it doesn’t, be sure you have Vault and some economy plugin like Essentials installed. I’ll test it myself in about half an hour as well

**Comment by Teomaniaforreal** [comment]
![image](https://user-images.githubusercontent.com/24739967/56219904-d3092280-6067-11e9-80ef-c96616920510.png)

**Comment by cjburkey01** [comment]
Yup, that looks like a problem on my end

**Comment by cjburkey01** [comment]
Should be fixed in https://github.com/cjburkey01/ClaimChunk/commit/fc06b2aafce3a5b1c7a5744a92bbc14b7041c4bf

I'll post a release later today when I tackle some more of these bugs. Thank you for the report
