### ISSUE TITLE
A Few Ideas (List Command, Max Claim Permission, etc) & Some Bugs (Unclaiming & Worldguard)

### ISSUE THREAD

**Issue by meowsome** [cjburkey01/ClaimChunk#37]
I hope this is the right place to write this, hahah. This plugin is awesome, but I have a few suggestions:
- Add a "list" command, where players can view a list of all chunks they own and coordinates as well.
- Add an "info" command to show information about the chunk the player is currently in.
- Add the ability to set the max amounts of chunks players can claim via permissions (e.g. 
claimchunk.maxclaims.[number])
- Add a "package" permission that enables all basic features for players, such as claiming, unclaiming, etc. Maybe call it claimchunk.use or claimchunk.player?
- Show the amount of money that you claimed the chunk for in the message displayed after claiming a chunk.
- Maybe reduce the number of messages that appear in console upon server start? Or add a "debug" option in the config that will make all these messages appear/disappear? I feel like it's a lot at the moment. I dunno.

And here's two bugs I noticed:
- When unclaiming the first chunk, the player is still refunded the "award" amount for unclaiming, even if the "first chunk free" option was enabled. This could give the player free money if they claim and unclaim repeatedly.
- The WorldGuard integration doesn't seem to be working? On startup it says "[ClaimChunk] WorldGuard support not enabled because the WorldGuard plugin was not found.", but I am 100% sure I am using the WorldGuard plugin on my server. Also the "chunk-claim" flag doesn't seem to show up in the flag list. Perhaps it's because I'm using an older version? I am running 6.2.1 (on a 1.12 server).

These are just a few things I thought would be cool when testing out the plugin today. Other than that, it's wonderful!

**Comment by cjburkey01** [comment]
These sounds cool, I'll try to get them implemented soon. On the subject of WorldGuard, you will need version 7 on 1.13 or later, the WorldGuard API changed too much between 1.12 and 1.13 to allow both versions to work easily.

**Comment by meowsome** [comment]
That was one fast reply, wow. That sucks that you need to have the 1.13 version, for now I'll just block the chunk command in the lobby area via worldguard. Sorry if it seems like this is a lot, it's just some ideas I had. I look forward to seeing them implemented!

**Comment by cjburkey01** [comment]
Yeah sorry about 1.13 but I completely forgot about WorldGuard's command blocking lol, that'll do it :)

**Comment by meowsome** [comment]
Hello, I found some more bugs! Is it alright if I post them here, or should I make a new "issue" thing?

- When putting water into a bucket, this appears in console: https://pastebin.com/3BCBR5dv
- When placing water from a bucket, this appears in console: https://pastebin.com/n2yrxsC6
- I believe the “blockCreeper” in config.yml blocks creeper explosions it in unclaimed territory as well as claimed territory.

**Comment by cjburkey01** [comment]
Oh boy

Could you move those bucket errors to another issue? That's a bug with older versions. Thank you

**Comment by cjburkey01** [comment]
I've created a separate issue for PvP: https://github.com/cjburkey01/ClaimChunk/issues/42
Debug spam: https://github.com/cjburkey01/ClaimChunk/issues/43
Rank-based claim limits: https://github.com/cjburkey01/ClaimChunk/issues/44
List command: https://github.com/cjburkey01/ClaimChunk/issues/45

Package permission was added in https://github.com/cjburkey01/ClaimChunk/commit/faa99cc13d82d68c113baf3681889cc7c9a34784

Todo:
- Info command
- Display cost of claim in message
- Fix players receiving refund for free first chunk

Let me know if I've left anything out 👍

**Comment by meowsome** [comment]
Awesome, sounds good. Thanks so much! I'll make the separate issue for the bucket errors.

**Comment by cjburkey01** [comment]
Thank you

**Comment by cjburkey01** [comment]
Added info command: https://github.com/cjburkey01/ClaimChunk/commit/53cff31382bd77f9fde7b01863c86ca95e81dc9e
Display claim cost and fix players receiving refund on free chunks: https://github.com/cjburkey01/ClaimChunk/commit/3ac3ed8c94f6f6ca70d4513cb437522d44f91705

I think that's it for this issue, if I forgot something feel free to reopen this or open a new issue
