### ISSUE TITLE
Admin Override

### ISSUE THREAD

**Issue by vulgarfate** [cjburkey01/ClaimChunk#40]
#33 had an issue which is the same as mine, but I'm on 0.0.8. Even if I'm opped, and I gave every permission to my Admin group (which I'm in), I cannot unclaim other peoples chunks as it says I do not own this chunk.

Currently, I have to shut down the server, remove it from the json file, and start the server again.

**Comment by cjburkey01** [comment]
Oh, yeah, I never actually added the ability to claim/unclaim chunks for other users. I wonder if I should allow claiming for other users, that would require a bit of work on the `/chunk claim` command but I could definitely do unclaiming.

**Comment by vulgarfate** [comment]
For me personally, even unclaiming (with/without economy refund) alone would be pretty damn awesome, if possible. If an admin is trying to claim a players claim, just an error saying "You must unclaim {players} chunk before you claim it." could work. Or maybe make the command something like `/chunk admin unclaim`, to make sure it doesn't interfere with the typical `/chunk unclaim`/make it easier? I have no idea how it works of course, and I don't know what's possible or easiest; whenever I try to look at Java I want to cry!

Anyway, thanks a lot man, and I'm excited for the addition!

**Comment by cjburkey01** [comment]
Haha that code is mostly my fault lol, Java’s meant to be a nice language. Ideally I’d fix it at some point, but that’s besides the point. I’ll just use this issue to track unclaiming other player’s chunks as an admin for now, a `/chunk adminclaim <ply>` might be better to keep everything as similar as possible

**Comment by cjburkey01** [comment]
Added admin unclaiming in https://github.com/cjburkey01/ClaimChunk/commit/faa99cc13d82d68c113baf3681889cc7c9a34784

I'll go ahead and say it's good for now. Feel free to reopen this if you feel like admin chunk claiming should be a thing.
