### ISSUE TITLE
Per-Rank Maximum Claims

### ISSUE THREAD

**Issue by cjburkey01** [cjburkey01/ClaimChunk#44]
Allow permissions such as `claimchunk.claim.<NUMBER>` to override the default limit in the config. For example, if the `ranks.json` has these ranks:
```json
[
  {
    "name": "boss",
    "claims": 100
  },
  {
    "name": "lame",
    "claims": 10
  }
]
```
and a player is granted the `claimchunk.claim.boss` permission, they will be able to claim 100 chunks. Likewise, a player with `claimchunk.claim.lame` can only claim 10 chunks.

Note: This would be incompatible with standard Bukkit permissions, so a permissions plugin would be required.

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/96aaae1b852e611f1203c5afb25ef2ff6cdb1c58

**Comment by meowsome** [comment]
Hi,
I can't get this to work. Is the permission "claimchunk.claim.<name>" like you listed in the post, or is it something different?
