### ISSUE TITLE
Command to List Claims in World

### ISSUE THREAD

**Issue by cjburkey01** [cjburkey01/ClaimChunk#45]
Add a command like `/claimchunk listchunks` to list all of (in page format) a player's claims in the current world. Possibly allow admins to use `/claimchunk listchunks [PLAYER]` to view other players' claims.

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/82b0ed864a08dab52234fb610770460a54085532

**Comment by meowsome** [comment]
I'm a little bit confused by the results of this. I have chunks claimed near X 278 and Z 631 on my server, but the listed chunks are nowhere near where the actual chunks are. Is this some error on my part, or a bug...?

![image](https://user-images.githubusercontent.com/20958440/57148359-72802200-6d97-11e9-9019-1ad3278716b0.png)

**Comment by cjburkey01** [comment]
Ah, those are chunk coordinates, so multiply by 16. I should make it much clearer (display both?) as well as list chunks in order of closeness to the executor.

**Comment by meowsome** [comment]
Oh okay sorry, I didn't realize that's what it was showing. Thank you for explaining. Displaying both would be cool :)

**Comment by cjburkey01** [comment]
Yeah it’s definitely confusing lol. I didn’t think about that
