### ISSUE TITLE
Bucket Fill / Empty Errors

### ISSUE THREAD

**Issue by meowsome** [cjburkey01/ClaimChunk#46]
(Moving this from my previous issue to this new one)
- When putting water into a bucket, this appears in console: https://pastebin.com/3BCBR5dv
- When placing water from a bucket, this appears in console: https://pastebin.com/n2yrxsC6

**Comment by cjburkey01** [comment]
For my own reference: Fix 1.12 (and below) bucket code

**Comment by cjburkey01** [comment]
Should be fixed https://github.com/cjburkey01/ClaimChunk/commit/0a0235a4711ebaf8cfc7013e79ebdcb082f98949
