### ISSUE TITLE
Stacking issue with other commands

### ISSUE THREAD

**Issue by testablebox048** [cjburkey01/ClaimChunk#47]
can't use /chunk claim because it says sub-command needed?

**Comment by cjburkey01** [comment]
I don't understand, could you take a screenshot of the message please?

**Comment by testablebox048** [comment]
watch this:
 2019-04-29 19-23-32.mp4
<https://drive.google.com/file/d/1n_oPqgNEWo1cVN-SiTde8-JkDjqFXMEt/view?usp=drive_web>
Thx for you're time
If you are still confused contact me again on discord:testablebox048#4659

**Comment by cjburkey01** [comment]
Ah, looks like you have a different plugin installed that adds a `/chunk` command. Could you do `/pl` and list what plugins you have installed?

**Comment by meowsome** [comment]
I just looked it up cuz I was curious and looks like it's WorldEdit: https://github.com/SBPrime/AsyncWorldEdit-Premium/wiki/Commands#direct-chunk-commands

**Comment by cjburkey01** [comment]
Hm, could you try using standard WorldEdit? I’ve tested it against that because of the WorldGuard integration but I’ve never tested AsyncWorldEdit with this plugin. I could add in an alias command to clear up ambiguity, like `/claim` or `/claimchunk`

**Comment by cjburkey01** [comment]
Here’s that issue: https://github.com/cjburkey01/ClaimChunk/issues/48 I’m going to close this one because it’s related to another plugin.

**Comment by testablebox048** [comment]
thx for the help
