### ISSUE TITLE
(Suggestion) Add disabled worlds option

### ISSUE THREAD

**Issue by vulgarfate** [cjburkey01/ClaimChunk#51]
My small server started growing and I've got Creative & Minigames worlds now. I'd like to be able to block claiming in these worlds if possible, just a simple config would be cool, like
"disabled-worlds:
  - Creative
  - Tutorial"
etc, or a command would be even cooler, something like `/chunk disable {world}`

**Comment by cjburkey01** [comment]
I really should add this.

The current "solution" is upgrade to 1.13+, install WorldGuard, and set the `chunk-claim` flag in the `__global__` region to `DENY`. Essentially it's a bit of work to disable the plugin in a world lol

**Comment by vulgarfate** [comment]
Yes, true haha! I was thinking of using WorldGuard in the meantime, I just thought I'd shoot the suggestion your way and see if you'd be interested in adding it :D Thanks man!

**Comment by cjburkey01** [comment]
Fixed in https://github.com/cjburkey01/ClaimChunk/commit/b4d8a331d18c8b0b07be903ce4d9b08624121fea

It'll be available in 0.0.9 which should be out in a few minutes because there's a security bug I fixed
