### ISSUE TITLE
Claim message keep comming up

### ISSUE THREAD

**Issue by MrmaximoExcssum** [cjburkey01/ClaimChunk#52]
If you interact with another plays claimed chunk and then walk in and out and have claim messages to display in action bar to true then if you walk in and out of another player claimed then the message that shows:  "You cannot edit this chunk" keep coming appearing

**Comment by cjburkey01** [comment]
Can I close this other issue? https://github.com/cjburkey01/ClaimChunk/issues/38

**Comment by MrmaximoExcssum** [comment]
No it is still not fixed

**Comment by cjburkey01** [comment]
Isn't this the same problem?

**Comment by cjburkey01** [comment]
Should be fixed in https://github.com/cjburkey01/ClaimChunk/commit/0f457cd0df11993f6aba4f2622eed2a63e609e3f

It'll be in 0.0.10 when that comes out
