### ISSUE TITLE
/chunk access <player> dont works in spigot version 1.14

### ISSUE THREAD

**Issue by MrmaximoExcssum** [cjburkey01/ClaimChunk#53]
/chunk access <player> doesn't work in spigot version 1.14 
Minecraft version: Spigot 1.14 
Plugin version: Latest *0.0.8*
-------
If u use /chunk access <player> the message will successfully display but the trusted player won't be able to interact with anything

**Comment by cjburkey01** [comment]
Does it work as expected for 1.13? I don't think I've been able to really test it. It could be a bug for 0.0.8 in general

**Comment by cjburkey01** [comment]
Could you paste  the contents of your `/plugins/ClaimChunk/data/playerData.json` file?

**Comment by cjburkey01** [comment]
Did you get this working?
