### ISSUE TITLE
Keep Current Territory's Owner Shown in Action Bar

### ISSUE THREAD

**Issue by cjburkey01** [cjburkey01/ClaimChunk#54]
Add a config option to display something like "Territory of <PLAYER>" on the action bar instead of displaying it for a few seconds and disappearing.

**Comment by MrmaximoExcssum** [comment]
Yes

**Comment by cjburkey01** [comment]
Unfortunately the system required to make this work could be a sizable performance impact on the server, I think this would be much better handled by an addon if necessary.
