### ISSUE TITLE
(Suggestion) '/chunk name' names (grouped) chunks individually

### ISSUE THREAD

**Issue by vulgarfate** [cjburkey01/ClaimChunk#55]
Hello again,

This is something I'd really love, if possible.

So, for example, I have my Main Base chunks, 10 all linked together named VulgarMainBase. Then, I have another 2 linked, claimed chunks some 500 blocks away at an XP farm, and I'd like to name it VulgarXPFarm, but of course, the name carries from VulgarMainBase. I'd like them to be named separately.

If this is possible, this would make me so happy, even though I mean nothing to you :stuck_out_tongue: 

Have a great day/evening :smile:

**Comment by cjburkey01** [comment]
So, when `/chunk name <NEW NAME>` is used, you'd like it to name all chunks touching that chunk you were in?

**Comment by vulgarfate** [comment]
Yeah, perfect, and if it's possible :D I'm sorry if I wasn't clear enough in my original posting

**Comment by cjburkey01** [comment]
Unfortunately, I don't think this feature would fit too well into the current system for the plugin. It would add a large overhead to each claim operation as well as storage and I'm not sure if it's worth that slowdown on the server's side. I am planning on creating an API that could possibly allow this feature so a theoretical addon to ClaimChunk could implement a feature like per-chunk name overrides. I also plan on creating a separate plugin like "ClaimChunk Addons", depending on the final API, I could try implementing it into that plugin once I've gotten it going.

Thanks for the suggestion :)
