### ISSUE TITLE
(Suggestion / Question) Towny implementation?

### ISSUE THREAD

**Issue by blazex224** [cjburkey01/ClaimChunk#56]
Hello,
First I'd like to say great job on the plugin so far. I have not used it, but the features look much more appealing than, say, GriefPrevention. Though GP is good, some players find it confusing, especially if they are not familiar with using plugins. This is simple. /chunk claim. So elegant.

I was wondering if you were planning on adding any integration with Towny. I'd like to try using Towny to promote players building towns, but using this plugin as the main way for players to claim land. I'd definitely use this plugin if this can work, and I'd be even more excited once that max claims permission is added if you are still considering it (I saw that another person suggested that).

Thanks!

**Comment by cjburkey01** [comment]
Thanks for the suggestion! I feel like if you have Towny, though, you really don't need this plugin. The point of ClaimChunk is to offer players a really simply way to protect their land in a way that doesn't promote fighting amongst players such as Factions. Towny is more of a collaborative concept, though, and while ClaimChunk has some features such as giving other players access to your chunks, it doesn't really promote the idea of full communities with roles and such. I do like the idea of a simpler Towny plugin, but I just don't think it fits too well with what ClaimChunk is meant to be.

Once again, thank you for the suggestion and I'm happy to hear you like the plugin so far :)
