### ISSUE TITLE
[Feature] Toggle to make protection only function whilst all teammates are offline.

### ISSUE THREAD

**Issue by ParadauxDev** [cjburkey01/ClaimChunk#61]
Essentially, I'd like a feature be where the chunks that you claim are only protected whilst the owner and all trusted users are offline

**Comment by cjburkey01** [comment]
I can add this feature such that if the owner is offline, editing is no longer restricted but requiring all accessors also to be offline might add considerable overhead to any player editing anything everywhere because of the event system. I'll try it but no promises on the second part

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/21f88058fded3bd150039ff03f1c3c0690afadd1
