### ISSUE TITLE
Setting permissions to none (For basic chunk-claims)

### ISSUE THREAD

**Issue by zaccieslak** [cjburkey01/ClaimChunk#64]
Just submitting the suggestion to subtract the function that players need to have a certain permission to claim chunks. I don't know if there's an easier way like changing permissions within the .yml, but yeah! Thanks so much for the work you've done and that you do.

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/507eceb79c463dd970094dce4bb103b0ea1c9248, should be available in 0.0.11 after some testing
