### ISSUE TITLE
Conncet With me

### ISSUE THREAD

**Issue by AKenator12** [cjburkey01/ClaimChunk#67]
iwant you to conect with me for bussiness give me your discord or your insta or twitter or fb :)
fast please <3

**Comment by cjburkey01** [comment]
The GitHub issues system is for problems with the plugin, please refrain from business requests. I can be reached at bulletlanguage@gmail.com

**Comment by AKenator12** [comment]
for money

**Comment by AKenator12** [comment]
man iwant you in bussines pm me discord
AKena#9421
