### ISSUE TITLE
Per-Chunk Access

### ISSUE THREAD

**Issue by cjburkey01** [cjburkey01/ClaimChunk#73]
Allow users to grant other users access to a specific chunk only

**Comment by EggLord54** [comment]
This would be awesome! :)

**Comment by JaHollYT** [comment]
Love the Idea!

**Comment by Rhayweth** [comment]
bump this up!

**Comment by cjburkey01** [comment]
I'm going to close this issue and move over to a more generic one here: https://github.com/cjburkey01/ClaimChunk/issues/147
