### ISSUE TITLE
Add Config Option To Allow Interaction in Claimed Chunks

### ISSUE THREAD

**Issue by ItszThomas** [cjburkey01/ClaimChunk#74]
Is it possible to make a extra option in the config:
We want to be able to choose if we can use doors, chests, buttons, pressure plates etc in claimed zones. So we want to be able to do these things in claimed zones but not break or place blocks. So making a config where we can choose to be able to use chest, buttons, etc in claimed zones would be very handy
thanks

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/70a07e76d8476f0e6a973cc40bfe6c0587578c63
