### ISSUE TITLE
Permissions Not Working

### ISSUE THREAD

**Issue by Shadowblitz16** [cjburkey01/ClaimChunk#79]
Spigot Version: 1.14.4
ClaimChunk Version: latest

so I have this permission file..
```
groups:
  USER:
    options:
      rank: '2'
      prefix: '&7'
      default: true
      permissions:
        - claimchunk.player : true
  ADMIN:
    inheritance:
    - USER
    options:
      rank: '1'
      prefix: '&c&lADMIN &d'
      default: false
      permissions:
        - claimchunk.admin : true
```

however I can't seem to use things like `/chunk claim` and `/chunk unclaim` when i first join.
when I op myself it works.

1. paste permissions into your permission.yml
2. start server
3. deop yourself
4. try to claim or unclaim a chunk

I should be able to use any command offered by `claimchunk.player`

I'm not sure if this is due to the plugin or not however I had to start asking questions somewhere
and as far as I can tell my permission.yml is correct

**Comment by cjburkey01** [comment]
Hm, I've never used the Spigot/Bukkit default permission system. If you install a permissions system and switch over to that does it work then? I have tested LuckyPerms and GroupManager with ClaimChunk so I know they work.

**Comment by cjburkey01** [comment]
If you don't want to use a permissions plugin, try just setting `disablePermissions` in the config under the `basic` category to `true` and see if all the players have access to the basic permissions then.

**Comment by Shadowblitz16** [comment]
@cjburkey01 
setting `disablePermissions` to true did it weird.

is there any simple plugins for spigot 1.14.4 that just remap the default permissions.yml?

**Comment by cjburkey01** [comment]
Not that I can think of, PermissionsEx used to be yml but I think they updated it and it's pretty complicated anyway

**Comment by cjburkey01** [comment]
I do recommend that you install a permissions plugin just to test if this works? I'm going to close this issue but if it's broken with a permissions plugin installed then feel free to reopen it.
