### ISSUE TITLE
allow items as chunk price

### ISSUE THREAD

**Issue by Shadowblitz16** [cjburkey01/ClaimChunk#81]
Please allow a list of items and the amount of each item for a chunk price

let's say I want to make each chunk cost either 1 emerald or 1 diamond or 5 gold or 25 iron

**Comment by cjburkey01** [comment]
Thank you for the suggestion but as it stands I don’t plan to implement a non-economy based method for purchasing chunks because it would end up being another branch of the plugin that I don’t have the resources to develop at the moment.
