### ISSUE TITLE
rename /access to /trust and make /untrust command

### ISSUE THREAD

**Issue by Shadowblitz16** [cjburkey01/ClaimChunk#82]
please rename `/access` to a more clear command like `/trust` it currently sound like your accessing someone else's chunks like it's a admin command.

also please add a `/untrust` command to untrust players.

**Comment by cjburkey01** [comment]
If you want to use `/trust` you can use Bukkit aliases, changing a fundamental command like that breaks backwards compatibility so I don’t want to modify it for everyone else.

**Comment by Shadowblitz16** [comment]
@cjburkey01  can we get a unaccess command then?

**Comment by cjburkey01** [comment]
You can use `/chunk access` again to revoke access, it’s a toggle command
