### ISSUE TITLE
Suggestion: make a /tnt-toggle feature

### ISSUE THREAD

**Issue by EggLord54** [cjburkey01/ClaimChunk#83]
**Is your feature request related to a problem? Please describe.**
It's frustrating not being able to construct a redstone machine that makes use of tnt (e.g. automatic wood and stone farms).

**Describe the solution you'd like**
the ability to toggle the explosion of tnt in *specific* claimed chunks you own via chat commands

**Describe alternatives you've considered**
It'd be awesome if we could have a solution such as "/claimchunk toggle-tnt false-true feature. This would be a much appreciated feature and make all my redstone wet dreams come true 💯 !

**Additional context**

**Comment by cjburkey01** [comment]
Added `/claimchunk tnt` in https://github.com/cjburkey01/ClaimChunk/commit/3e668b2845d1d2e8cb8ae05a9717640296fd25bf
