### ISSUE TITLE
Creeper and TNT block damage disabled outside of claims 

### ISSUE THREAD

**Issue by Yofou** [cjburkey01/ClaimChunk#85]
**Versions**
Spigot Version:
ClaimChunk Version:

**Describe the bug**
For some reason, every chunk is protected from TNT and creepers explosions (block damage) rather than just inside the claim

**Expected behavior**
TNT and creeper explosions (block damage) only disabled inside the claim rather than outside it too

**Additional context**
None

**Comment by cjburkey01** [comment]
Funnily enough this was a bug for two years before anyone found it, and you just so happened to report it the day after I fixed it in the soon-to-be released 0.0.16 in fa92906

**Comment by Marcel2508** [comment]
@cjburkey01 Hi, when do you think this update will be released? I would really need this working ;D,

**Comment by cjburkey01** [comment]
You can get a preview snapshot here: https://cdn.discordapp.com/attachments/567470931098861619/605894953914073130/claimchunk-0.0.16-SNAPSHOT.jar

I can't promise how stable it is but it should fix that issue at least lol. Definitely make a backup of your data to be safe
