### ISSUE TITLE
Animals can be killed with arrows inside claimed chunks

### ISSUE THREAD

**Issue by ratawar** [cjburkey01/ClaimChunk#86]
Just tested that, even though animals cannot be killed by hand nor with melee weapons inside a claimed chunk and option `protectAnimals: true`, they can receive damage and therefore be killed with bows and crossbows. Wondered if it's an issue that could be taken in consideration. Awesome plugin, many thanks!

**Comment by cjburkey01** [comment]
Should be fixed in https://github.com/cjburkey01/ClaimChunk/commit/da9d1c2828f08d3b2eb55f4ac8d2f32c02e9e356
