### ISSUE TITLE
Customize Command Descriptions in Messages File

### ISSUE THREAD

**Issue by OverBrave** [cjburkey01/ClaimChunk#91]
**Is your feature request related to a problem? Please describe.**
Can you add help message to config.yml?

**Comment by cjburkey01** [comment]
You can customize the help messages under the `messages` section of the `config.yml` file

**Comment by OverBrave** [comment]
Where? I can't see?

https://hastebin.com/suheyiqopi.sql

**Comment by OverBrave** [comment]
How change this help message?
![image](https://user-images.githubusercontent.com/47111280/64244040-095d1680-cf11-11e9-904f-2922eec645ce.png)

**Comment by cjburkey01** [comment]
Whoops, I misunderstood sorry. This is for the descriptions of commands

**Comment by cjburkey01** [comment]
Added in https://github.com/cjburkey01/ClaimChunk/commit/058840461e022ecbce55842488f8d8806ae453d3
