### ISSUE TITLE
Armor Stands, Frames & Some Mobs Can be attacked/destroyed

### ISSUE THREAD

**Issue by AlureonTM** [cjburkey01/ClaimChunk#92]
**Versions**
Spigot Version: Paper 1.14.4
ClaimChunk Version: Latest

**Describe the bug**
Armor stands can be knocked out of chunks and then destroyed when creepers explode inside chunks frames and the items inside them break. And some mobs such as villagers can be killed inside the chunks. 

**To Reproduce**
1. Have a creeper go into area with item frames and have it blow up
2. Put armor stand with armor inside of a chunk and have another player hit it and bounce it until its out of the chunk
3. Hit villagers inside the chunk

**Expected behavior**
Frames not to break from explosions, villagers & any non-hostile mob to not take damage inside other players chunks and for armor stands to not be able to be hit at all by anyone not given access to in the chunk

**Additional context**
As confirmed by other people it is NOT a config issue. My config can be seen here:
https://pastebin.com/SvDNF32X

**Comment by cjburkey01** [comment]
Should be fixed in https://github.com/cjburkey01/ClaimChunk/commit/da9d1c2828f08d3b2eb55f4ac8d2f32c02e9e356
