### ISSUE TITLE
Console complains while using SQL after a period of time.

### ISSUE THREAD

**Issue by ExcerptNovela** [cjburkey01/ClaimChunk#95]
**Versions**
Spigot Version: Paper 186
ClaimChunk Version: 0.0.15

**Describe the bug**
08.09 18:57:17 [Server] WARN com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
08.09 18:57:17 [Server] WARN at sun.reflect.GeneratedConstructorAccessor153.newInstance(Unknown Source)
08.09 18:57:17 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
08.09 18:57:17 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.Util.getInstance(Util.java:408)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4067)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4036)
08.09 18:57:17 [Server] WARN at com.cjburkey.claimchunk.data.newdata.SqlBacking.prep(SqlBacking.java:42)
08.09 18:57:17 [Server] WARN at com.cjburkey.claimchunk.data.newdata.MySQLDataHandler.isChunkClaimed(MySQLDataHandler.java:176)
08.09 18:57:17 [Server] WARN at com.cjburkey.claimchunk.chunk.ChunkHandler.isClaimed(ChunkHandler.java:93)
08.09 18:57:17 [Server] WARN at com.cjburkey.claimchunk.event.PlayerMovementHandler.onPlayerMove(PlayerMovementHandler.java:39)
08.09 18:57:17 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor276.execute(Unknown Source)
08.09 18:57:17 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
08.09 18:57:17 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
08.09 18:57:17 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
08.09 18:57:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1103)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923)
08.09 18:57:17 [Server] WARN at java.lang.Thread.run(Thread.java:748)
08.09 18:57:17 [Server] WARN Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 15,714,832 milliseconds ago. The last packet sent successfully to the server was 15,714,833 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
08.09 18:57:17 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
08.09 18:57:17 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
08.09 18:57:17 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
08.09 18:57:17 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3751)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
08.09 18:57:17 [Server] WARN at com.cjburkey.claimchunk.data.newdata.MySQLDataHandler.hasPlayer(MySQLDataHandler.java:518)
08.09 18:57:17 [Server] WARN at com.cjburkey.claimchunk.player.PlayerHandler.onJoin(PlayerHandler.java:87)
08.09 18:57:17 [Server] WARN at com.cjburkey.claimchunk.event.PlayerConnectionHandler.onPlayerJoin(PlayerConnectionHandler.java:15)
08.09 18:57:17 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor260.execute(Unknown Source)
08.09 18:57:17 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
08.09 18:57:17 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
08.09 18:57:17 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
08.09 18:57:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:191)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1232)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075)
08.09 18:57:17 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919)
08.09 18:57:17 [Server] WARN ... 1 more
08.09 18:57:17 [Server] WARN Caused by: java.net.SocketException: Connection reset
08.09 18:57:17 [Server] WARN at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
08.09 18:57:17 [Server] WARN at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
08.09 18:57:17 [Server] WARN at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
08.09 18:57:17 [Server] WARN at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
08.09 18:57:17 [Server] WARN at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3733)
08.09 18:57:17 [Server] WARN ... 23 more
08.09 18:57:17 [Server] ERROR Failed to determine if chunk was claimed

**Additional context**
The hosting platform is Shockbyte, minecraft version is 1.14.4. The server is also running World Guard, and World Edit. The only other plugin using the SQL database is Dynmap.

**Comment by cjburkey01** [comment]
It looks like the connection is automatically getting closed. I think this may be an issue with the way I handle the connection management and should be fixed with the update I started working on a month ago.

I swear I’ll get to finishing it at some point lol

**Comment by cjburkey01** [comment]
Note to myself: Update the connection singleton when attempting to connect; the current system does not work

**Comment by cjburkey01** [comment]
whoops didn't mean to close

**Comment by cjburkey01** [comment]
Fixed in https://github.com/cjburkey01/ClaimChunk/commit/fdc25e17179635faeb6ac749752f739cc3bdf3aa
