### ISSUE TITLE
featherboard integration

### ISSUE THREAD

**Issue by kirveq** [cjburkey01/ClaimChunk#97]
I want the featherboard plugin to show the name of the claim owner in the menu on the right.
and I want the claim members to appear if there is a bottom line

**Comment by cjburkey01** [comment]
Integration is a good idea but maintaining integrations with a bunch of other plugins is a little too taxing for me to manage right now.

If someone else is willing to do it then feel free to ask me any questions on Discord and I’ll try to help as best I can.

**Comment by kirveq** [comment]
I'm writing to you in discord. wanted a lot of things to develop plugin, but you do not answer and do not help?

**Comment by cjburkey01** [comment]
Unfortunately I’m not able to be as active as I’d like to be, but I try to check it every few days at least

**Comment by kirveq** [comment]
Okay, but I look forward to you
